- hosts: myhost
  become: yes #作為root執行 放這會作用每個task
  tasks:
    - name: set sudoers nopassword
      ansible.builtin.lineinfile:
        create: yes
        path: /etc/sudoers.d/myOverrides
        state: present
        line: 'vagrant ALL=(ALL) NOPASSWD: ALL'
    - name: set sudoers default editor
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        state: present
        line: 'Defaults  editor=/usr/bin/vim'
    - name: set timezone
      ansible.builtin.shell:
        cmd: timedatectl set-timezone Asia/Taipei
    - name: Update repositories cache
      apt:
        update_cache: yes
    - name: Install the package "git"
      apt:
        name: git
    - name: Install the package "zsh"
      apt:
        name: zsh
    - name: Install the package "unzip"
      apt:
        name: unzip
    - name: Install the package "software-properties-common"
      apt:
        name: software-properties-common
    - name: Install the package "jq"
      apt:
        name: jq
    - name: set git config
      ansible.builtin.shell: |
        git config --global user.name "Mr. Dai"
        git config --global user.email xanxus@example.com
        git config --global core.editor "vim"
    - name: Download oh-my-zsh
      register: result
      become_user: vagrant
      get_url:
        url: https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh
        dest: ~/
        mode: '0600'
    - name: install oh-my-zsh
      become_user: vagrant
      register: result
      async: 15
      poll: 0
      ansible.builtin.shell: |
        sh ~/install.sh
    - name: set oh-my-zsh
      async: 15
      poll: 5
      register: scrout
      ansible.builtin.shell: |
        chsh -s /bin/zsh vagrant
        zsh
    - name: Checking the Job Status
      async_status:
        jid: "{{ scrout.ansible_job_id }}"
      register: job_result
      until: job_result.finished
      retries: 10
    - name: Print return information from the previous task
      ansible.builtin.debug:
        var: job_result